# Generated by Django 5.0.4 on 2025-06-28 18:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=255)),
                ('period', models.PositiveIntegerField()),
                ('actual', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"content"."subscription"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('payment_id', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('transaction_type', models.IntegerField()),
                ('starts', models.DateTimeField(blank=True, null=True)),
                ('ends', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"content"."transaction"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('auto_pay_id', models.CharField(max_length=255)),
                ('expires', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"content"."user_subscription"',
                'managed': False,
            },
        ),
    ]
