"""Added start & end columns to Transaction

Revision ID: 95057a49c716
Revises: ccfaa6e4a85d
Create Date: 2025-06-21 20:59:28.282762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95057a49c716'
down_revision: Union[str, None] = 'ccfaa6e4a85d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('starts', sa.DateTime(), nullable=True), schema='content')
    op.add_column('transaction', sa.Column('ends', sa.DateTime(), nullable=True), schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'ends', schema='content')
    op.drop_column('transaction', 'starts', schema='content')
    # ### end Alembic commands ###
