"""Updated datetime columns naming

Revision ID: b7c77afc27f9
Revises: 08bb5ecca210
Create Date: 2025-06-14 15:23:09.895907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7c77afc27f9'
down_revision: Union[str, None] = '08bb5ecca210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('created_at', sa.DateTime(), nullable=True), schema='content')
    op.add_column('subscription', sa.Column('modified_at', sa.DateTime(), nullable=True), schema='content')
    op.drop_column('subscription', 'modified', schema='content')
    op.drop_column('subscription', 'created', schema='content')
    op.add_column('transaction', sa.Column('created_at', sa.DateTime(), nullable=True), schema='content')
    op.add_column('transaction', sa.Column('modified_at', sa.DateTime(), nullable=True), schema='content')
    op.drop_column('transaction', 'modified', schema='content')
    op.drop_column('transaction', 'created', schema='content')
    op.add_column('user_subscription', sa.Column('expires_at', sa.DateTime(), nullable=False), schema='content')
    op.add_column('user_subscription', sa.Column('created_at', sa.DateTime(), nullable=True), schema='content')
    op.add_column('user_subscription', sa.Column('modified_at', sa.DateTime(), nullable=True), schema='content')
    op.drop_column('user_subscription', 'expires', schema='content')
    op.drop_column('user_subscription', 'modified', schema='content')
    op.drop_column('user_subscription', 'created', schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscription', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='content')
    op.add_column('user_subscription', sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='content')
    op.add_column('user_subscription', sa.Column('expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=False), schema='content')
    op.drop_column('user_subscription', 'modified_at', schema='content')
    op.drop_column('user_subscription', 'created_at', schema='content')
    op.drop_column('user_subscription', 'expires_at', schema='content')
    op.add_column('transaction', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='content')
    op.add_column('transaction', sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='content')
    op.drop_column('transaction', 'modified_at', schema='content')
    op.drop_column('transaction', 'created_at', schema='content')
    op.add_column('subscription', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='content')
    op.add_column('subscription', sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='content')
    op.drop_column('subscription', 'modified_at', schema='content')
    op.drop_column('subscription', 'created_at', schema='content')
    # ### end Alembic commands ###
