"""Made auto_pay_id nullable as it cannot be known by the time of user_subs creation

Revision ID: ccfaa6e4a85d
Revises: e006c832b622
Create Date: 2025-06-19 17:53:24.723587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfaa6e4a85d'
down_revision: Union[str, None] = 'e006c832b622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subscription', 'auto_pay_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subscription', 'auto_pay_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='content')
    # ### end Alembic commands ###
