"""Refined database scheme

Revision ID: e006c832b622
Revises: b7c77afc27f9
Create Date: 2025-06-17 21:26:28.701973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e006c832b622'
down_revision: Union[str, None] = 'b7c77afc27f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('actual', sa.Boolean(), nullable=False), schema='content')
    op.add_column('subscription', sa.Column('name', sa.String(255), nullable=False), schema='content')
    op.add_column('subscription', sa.Column('description', sa.Text(), nullable=True), schema='content')
    op.add_column('subscription', sa.Column('created', sa.DateTime(), nullable=True), schema='content')
    op.add_column('subscription', sa.Column('modified', sa.DateTime(), nullable=True), schema='content')
    op.drop_column('subscription', 'created_at', schema='content')
    op.drop_column('subscription', 'modified_at', schema='content')
    op.add_column('transaction', sa.Column('user_subscription_id', sa.Uuid(), nullable=True), schema='content')
    op.add_column('transaction', sa.Column('transaction_type', sa.Integer(), nullable=False), schema='content')
    op.add_column('transaction', sa.Column('created', sa.DateTime(), nullable=True), schema='content')
    op.add_column('transaction', sa.Column('modified', sa.DateTime(), nullable=True), schema='content')
    op.drop_constraint(op.f('transaction_subscription_id_fkey'), 'transaction', schema='content', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'user_subscription', ['user_subscription_id'], ['id'], source_schema='content', referent_schema='content')
    op.drop_column('transaction', 'subscription_id', schema='content')
    op.drop_column('transaction', 'modified_at', schema='content')
    op.drop_column('transaction', 'created_at', schema='content')
    op.drop_column('transaction', 'idempotence_key', schema='content')
    op.add_column('user_subscription', sa.Column('expires', sa.DateTime(), nullable=False), schema='content')
    op.add_column('user_subscription', sa.Column('created', sa.DateTime(), nullable=True), schema='content')
    op.add_column('user_subscription', sa.Column('modified', sa.DateTime(), nullable=True), schema='content')
    op.drop_constraint(op.f('user_subscription_subscription_id_fkey'), 'user_subscription', schema='content', type_='foreignkey')
    op.create_foreign_key(None, 'user_subscription', 'subscription', ['subscription_id'], ['id'], source_schema='content', referent_schema='content')
    op.drop_column('user_subscription', 'expires_at', schema='content')
    op.drop_column('user_subscription', 'created_at', schema='content')
    op.drop_column('user_subscription', 'modified_at', schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscription', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='content')
    op.add_column('user_subscription', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='content')
    op.add_column('user_subscription', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False), schema='content')
    op.drop_constraint(None, 'user_subscription', schema='content', type_='foreignkey')
    op.create_foreign_key(op.f('user_subscription_subscription_id_fkey'), 'user_subscription', 'subscription', ['subscription_id'], ['id'], source_schema='content', referent_schema='content', ondelete='CASCADE')
    op.drop_column('user_subscription', 'modified', schema='content')
    op.drop_column('user_subscription', 'created', schema='content')
    op.drop_column('user_subscription', 'expires', schema='content')
    op.add_column('transaction', sa.Column('idempotence_key', sa.VARCHAR(), autoincrement=False, nullable=False), schema='content')
    op.add_column('transaction', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='content')
    op.add_column('transaction', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='content')
    op.add_column('transaction', sa.Column('subscription_id', sa.UUID(), autoincrement=False, nullable=True), schema='content')
    op.drop_constraint(None, 'transaction', schema='content', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_subscription_id_fkey'), 'transaction', 'subscription', ['subscription_id'], ['id'], source_schema='content', referent_schema='content')
    op.drop_column('transaction', 'modified', schema='content')
    op.drop_column('transaction', 'created', schema='content')
    op.drop_column('transaction', 'transaction_type', schema='content')
    op.drop_column('transaction', 'user_subscription_id', schema='content')
    op.add_column('subscription', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='content')
    op.add_column('subscription', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='content')
    op.drop_column('subscription', 'modified', schema='content')
    op.drop_column('subscription', 'created', schema='content')
    op.drop_column('subscription', 'description', schema='content')
    op.drop_column('subscription', 'name', schema='content')
    op.drop_column('subscription', 'actual', schema='content')
    # ### end Alembic commands ###
