# Generated by Django 4.1.13 on 2025-06-01 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
                'db_table': 'content"."content',
            },
        ),
        migrations.CreateModel(
            name='TemplateDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('template', models.TextField()),
                ('template_type', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'db_table': 'content"."template',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEventDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('period', models.IntegerField(verbose_name='Период (сек)')),
                ('next_send', models.DateTimeField(verbose_name='Следующая отправка')),
                ('once', models.BooleanField(default=False, verbose_name='Одноразовая')),
                ('receiver_group_name', models.CharField(default='all', max_length=255, verbose_name='Группа получателей')),
                ('send_by', models.CharField(choices=[('email', 'Email'), ('websocket', 'WebSocket')], default='email', max_length=10, verbose_name='Способ отправки')),
                ('template', models.ForeignKey(db_column='template_id', on_delete=django.db.models.deletion.CASCADE, to='notifications_app.templatedb')),
            ],
            options={
                'verbose_name': 'Запланированная рассылка',
                'verbose_name_plural': 'Запланированные рассылки',
                'db_table': 'content"."schedule_notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('send_by', models.CharField(choices=[('email', 'Email'), ('websocket', 'WebSocket')], default='email', max_length=10, verbose_name='Способ отправки')),
                ('to_id', models.CharField(help_text="ID пользователя или 'all' для всех", max_length=255, verbose_name='Получатель')),
                ('template', models.ForeignKey(db_column='template_id', on_delete=django.db.models.deletion.CASCADE, to='notifications_app.templatedb')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'content"."notification',
            },
        ),
    ]
